name: Deploy to FTP
on:
  push:
    branches:
      - main # O la rama que uses para producción

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🛠️ Install and Build
        # Si usas React/Next.js, esto genera la carpeta 'dist' o 'out'
        run: |
          npm install
          npm run build 

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ # Asegúrate de que esta sea tu carpeta de salida